# change "REST_CLIENT_HOSTNAME" & @port "PORT" in .env file
@host = {{$dotenv REST_CLIENT_HOSTNAME}}:{{$dotenv PORT}}

###
# @desc     >bucketlist API
# @route    /api/bucket-list
### 
GET {{host}}/api/bucketlist
###
POST {{host}}/api/bucketlist
content-type: application/json

{
    "name": "Go to America"
}
###
PUT {{host}}/api/bucketlist/1
content-type: application/json

{
    "name": "Go to America",
    "isDone": false
}
###
DELETE {{host}}/api/bucketlist/1
###

