# change "REST_CLIENT_HOSTNAME" & @port "PORT" in .env file
@host = {{$dotenv REST_CLIENT_HOSTNAME}}:{{$dotenv PORT}}

###
# @desc     >bucketlist API
# @route    /api/bucket-list
### 
GET {{host}}/api/bucketlist
###
POST {{host}}/api/bucketlist
content-type: application/json

{
    "name": "Go to America"
}
###
PUT {{host}}/api/bucketlist/6215cb6a5bd6964049453808
content-type: application/json

{
    "name": "NYE",
    "isDone": true
}
###
DELETE {{host}}/api/bucketlist/6215c92d082de1ebd7fab944
###

