# This file act as an API Documentation
# Request inside this file can be send using VSCode Extension by name "REST Client"
# Regards, Muhammad Azmi Adhani

# change "REST_CLIENT_HOSTNAME" & @port "PORT" in .env file
@host = {{$dotenv REST_CLIENT_HOSTNAME}}:{{$dotenv PORT}}
###

# @API      auth
# @route    /api/auth
### 
# @desc         Sign Up for User
POST {{host}}/api/auth/signup
content-type: application/json

{
    "email": "azmiadhani3@gmail.com",
    "password": "azmiadhani"
}
###
# @desc         Log In for User
POST {{host}}/api/auth/login
content-type: application/json

{
    "email": "azmiadhani3@gmail.com",
    "password": "azmiadhani"
}
###

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDczNDQwNDEsImV4cCI6MTY0NzM0NzY0MSwiYXVkIjoiNjIzMDc5OTNmN2E3MmU5NTdiN2QzOTNlIiwiaXNzIjoiaHR0cHM6Ly9hem1pYWRoYW5pLmNvbSJ9.jbf7tNRLfKOsBvtlHcpsi6J39Xhj7GtJ0JroFrk3wTI
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDczNDQwNDEsImV4cCI6MTY3ODkwMTY0MSwiYXVkIjoiNjIzMDc5OTNmN2E3MmU5NTdiN2QzOTNlIiwiaXNzIjoiaHR0cHM6Ly9hem1pYWRoYW5pLmNvbSJ9.Obrp5AYOOOidU1b6cNCe03saIi3oygqdzFLwgeZsAMs

# @desc         Refresh Token
POST {{host}}/api/auth/refresh-token
content-type: application/json

{
    "refreshToken" : "{{refreshToken}}"
}
###

# @API      bucketlist
# @route    /api/bucket-list
### 
# @desc         Get all bucketlists
GET {{host}}/api/bucketlist
Authorization: Bearer {{accessToken}}
###
# @desc         Insert a new bucketlist
POST {{host}}/api/bucketlist
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "name": "Go to yeyeye",
    "isDone": true
}
###
@bucketlistId = 622ac8f3a8fec7c7524b2e7f
# @desc         Update a bucketlist
PUT {{host}}/api/bucketlist/{{bucketlistId}}
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "name": "NYE",
    "isDone": true
}
###
# @desc         Delete a bucketlist
DELETE {{host}}/api/bucketlist/{{bucketlistId}}
Authorization: Bearer {{accessToken}}
###