# This file act as an API Documentation
# Request inside this file can be send using VSCode Extension by name "REST Client"
# Regards, Muhammad Azmi Adhani

# change "REST_CLIENT_HOSTNAME" & @port "PORT" in .env file
@host = {{$dotenv REST_CLIENT_HOSTNAME}}:{{$dotenv PORT}}
###

# @API      auth
# @route    /api/auth
### 
# @desc         Sign Up for User
POST {{host}}/api/auth/signup
content-type: application/json

{
    "email": "azmiadhani2@gmail.com",
    "password": "azmiadhani"
}
###
# @desc         Log In for User
POST {{host}}/api/auth/login
content-type: application/json

{
    "email": "azmiadhani@gmail.com",
    "password": "azmiadhani"
}
###

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDY5NzExMTEsImV4cCI6MTY0Njk3NDcxMSwiYXVkIjoiNjIyODIzZTJmNjQxNDQ1NTQ2NTMxMTQ4IiwiaXNzIjoiaHR0cHM6Ly9hem1pYWRoYW5pLmNvbSJ9.vKAJV_gMokT3ENFyqvUlfFokTjbVPbcUHU_5Z9VhRdE
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDY4OTg2MjksImV4cCI6MTY3ODQ1NjIyOSwiYXVkIjoiNjIyODIzZTJmNjQxNDQ1NTQ2NTMxMTQ4IiwiaXNzIjoiaHR0cHM6Ly9hem1pYWRoYW5pLmNvbSJ9.TvLmPhN2sYuKLJvODE4qgTEus3MB_WZJIfCKb4pSBoA

# @desc         Refresh Token
POST {{host}}/api/auth/refresh-token
content-type: application/json

{
    "refreshToken" : "{{refreshToken}}"
}
###

# @API      bucketlist
# @route    /api/bucket-list
### 
# @desc         Get all bucketlists
GET {{host}}/api/bucketlist
Authorization: Bearer {{accessToken}}
###
# @desc         Insert a new bucketlist
POST {{host}}/api/bucketlist
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "name": "Go to yeyeye",
    "isDone": true
}
###
@bucketlistId = 622ac8f3a8fec7c7524b2e7f
# @desc         Update a bucketlist
PUT {{host}}/api/bucketlist/{{bucketlistId}}
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "name": "NYE",
    "isDone": true
}
###
# @desc         Delete a bucketlist
DELETE {{host}}/api/bucketlist/{{bucketlistId}}
Authorization: Bearer {{accessToken}}
###